// AUTOGENERATED
package tdlib

import (
    "encoding/json"
)

const (
    Type404: = "Found"
)

const (
    Constructor404: = "404:"
)

// 
type 404: struct{
    meta
}

func (*404:) GetType() string {
    return Type404:
}

func (*404:) GetConstructor() string {
    return Constructor404:
}

func (entity *404:) MarshalJSON() ([]byte, error) {
    entity.meta.MetaType = entity.GetConstructor()

    type stub 404:

    return json.Marshal((*stub)(entity))
}

