// AUTOGENERATED
package tdlib

import (
    "encoding/json"
    "fmt"
)

func Unmarshal404:(data json.RawMessage) (*404:, error) {
    var resp 404:
    err := json.Unmarshal(data, &resp)
    return &resp, err
}

func UnmarshalType(data json.RawMessage) (Type, error) {
    var meta meta
    err := json.Unmarshal(data, &meta)
    if err != nil {
        return nil, err
    }

    switch meta.MetaType {
    case Constructor404::
        return Unmarshal404:(data)

    default:
        return nil, fmt.Errorf("Error unmarshaling. Unknown type: " +  meta.MetaType)
    }
}
